# Generated by Django 5.1.2 on 2024-11-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.JSONField(default=list),
        ),
    ]
