# Generated by Django 5.1.2 on 2024-10-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_downvoted_by_post_upvoted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downvoted_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvoted_by',
        ),
    ]
