# Generated by Django 5.1.2 on 2024-11-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
    ]
